/**
 * Converts vehicle photos in /vehicle-images into small WebP files for the app
 * and regenerates src/data/vehicleImages.js. Run with: npm run images
 */
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';
import { VEHICLES } from '../src/data/vehicles.js';

const SRC = 'vehicle-images';
const OUT = 'src/assets/vehicles';
const SIZES = [640, 1200];
const norm = (s) => s.toLowerCase().replace(/\.[a-z0-9]+$/, '').replace(/[^a-z0-9]+/g, '');

fs.mkdirSync(OUT, { recursive: true });
const files = fs.readdirSync(SRC).filter((f) => /\.(jpe?g|png|webp)$/i.test(f));
const found = {};

for (const file of files) {
  const key = norm(file);
  const v = VEHICLES.find((x) => norm(x.name) === key || norm(x.id) === key);
  if (!v) { console.warn(`Skipped "${file}": no vehicle with that name or id.`); continue; }
  for (const w of SIZES) {
    // Transparent cutouts: trim empty padding, keep a small even margin, keep the alpha channel.
    const trimmed = await sharp(path.join(SRC, file)).trim({ threshold: 10 }).toBuffer();
    const meta = await sharp(trimmed).metadata();
    const pad = Math.round(Math.max(meta.width, meta.height) * 0.02);
    await sharp(trimmed)
      .extend({ top: pad, bottom: pad, left: pad, right: pad, background: { r: 0, g: 0, b: 0, alpha: 0 } })
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: w > 800 ? 80 : 82, alphaQuality: 90 })
      .toFile(path.join(OUT, `${v.id}-${w}.webp`));
  }
  found[v.id] = true;
  console.log(`✓ ${v.name}`);
}

const ids = VEHICLES.map((v) => v.id).filter((id) => found[id] || (fs.existsSync(path.join(OUT, `${id}-640.webp`)) && fs.existsSync(path.join(OUT, `${id}-1200.webp`))));
const camel = (id) => id.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const lines = [
  '// Generated by scripts/optimize-images.mjs. Do not edit by hand: run `npm run images`.',
  ...ids.flatMap((id) => [`import ${camel(id)}Sm from '../assets/vehicles/${id}-640.webp';`, `import ${camel(id)}Lg from '../assets/vehicles/${id}-1200.webp';`]),
  '',
  'export const VEHICLE_IMAGES = {',
  ...ids.map((id) => `  '${id}': { sm: ${camel(id)}Sm, lg: ${camel(id)}Lg },`),
  '};',
  '',
  '/** Transparent cutout for a vehicle, or null (the UI then falls back to vector art). */',
  'export const vehicleImage = (id) => VEHICLE_IMAGES[id] || null;',
  '',
];
fs.writeFileSync('src/data/vehicleImages.js', lines.join('\n'));
const missing = VEHICLES.filter((v) => !ids.includes(v.id)).map((v) => v.name);
console.log(`\n${ids.length}/20 vehicles have photos.${missing.length ? ` Missing: ${missing.join(', ')}` : ''}`);
